name: data

on: [push]

jobs:
  execute-python-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run script
      run: python build_data.py
    - name: Commit and push if changes to data.json
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add data.json
        git commit -m "Update data.json with new timestamp" || echo "No changes to commit"
        git push